### ISSUE TITLE
Script def writeAddress_D() but seems slow . help me thanks you

### ISSUE THREAD

**Issue by tuhieucamlam** [nos86/FX1N#1]
def writeAddress_D(self, address, value):
        v = "{:04X}".format(value)
        msg = '1'+"{:04X}".format(address*2+0x1000)+"{:02X}".format(2)+"{}".format(v[2:4])+"{}".format(v[0:2])
        return self.checkACK(self.com_writedata(payload=msg, response_size= 2))

**Comment by nos86** [comment]
Hello tuhieucamlam,
please use dev branch for your project.

Master is out-of-date and it contains a very first draft of protocol implementation.
I use dev-branch without problem and it's very fast. 
By the way consider that the communication speed is limited by PLC.

Salvo

**Comment by tuhieucamlam** [comment]
Hello  Salvo  ,

I think it's my Write problem, not the device but I use other software, the
speed is fast.

I read and write .

Please see my script help !

Thank you.



Vào Th 2, 2 thg 11, 2020 vào lúc 01:14 Salvo Musumeci <
notifications@github.com> đã viết:

**Comment by tuhieucamlam** [comment]
Hello  Salvo  ,

sorry when I am missing this part

def readAddress_D(self, address, data_read=1): when reading alone fast speed
def writeAddress_D(self, address, value):  when reading alone slow speed

Thank you

Vào Th 2, 2 thg 11, 2020 vào lúc 10:04 Hiếu Nguyễn <tuhieucamlam@gmail.com>
đã viết:
